sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f ./Dockerfile.dev -t ranggarifqi/qashir-backend-dev .

script:
  - docker run -e CGO_ENABLED=0 ranggarifqi/qashir-backend-dev make test

deploy:
  provider: script
  script:
    - docker build -t ranggarifqi/qashir-backend .
    # Login to heroku
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku auth:token
    - heroku container:login
    - heroku container:push web
    - heroku container:release web
  on:
    branch: main
