sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f ./Dockerfile.dev -t ranggarifqi/qashir_api_dev .

script:
  - docker run -e CGO_ENABLED=0 ranggarifqi/qashir_api_dev make test